# os: osx # enable this if you need macOS support
language: ruby
rvm:
  - 2.6.3
deploy:
  - provider: rubygems
    api_key:
      secure: HiYnlWSfaQo9+jezq3PrxNykDSCIIFDP1oxLVz77vsXRh8pJRCdD6NL8SFlHTT6OX40pMWKjK05F+pTcGtsqqmoe7LS/s+lBYsVxEaHLkDz/JKaOLrhnm9P0V3hYxj239o9St1Ro58wKbQYWjyLXdvKk5xVMrp9XbmKYEGpimNk4YUYmvYA9+pVVTSUdlt15L109wC/92tJigTaNNMn3T2KgetdgZQEUn+8mlv1hZvb6fcCdPn5PCP/5nZAGL9dRuL16ztMQhlGQCvtutIU5dbsZsaNg/WF5JReCgUbF+mnUAImmRO9oKNQJAcp3PAhlJ73GeZyewQD7saWqQqYoZ4nkQQW6siqKRE9phdWoe2hU/AlAhpz3ZcJAgPI22MX2pHwwfEwTHfq9S4bsH6ZzVUbY8RMuEEDFwgly74AZzak2TP0bpGMziP1UzgmsPQYiNCT4EUvIQfh40oC0pi1/XOLT9vqFuCf2GcFKtnLQJGlBxuPEIvZfqNDWHts5NuMP8JKAbMB5lUFjHEGDkEmjpT8ebkHxLEivsXhWSHG9i0mO8obbNJCKJQ6n32dtyPY0twP/PjEBYmBamcLIiLACuens578GoF6Bhs6DSGF9zd6uHKQqORDpi4pp6QcUFgqUkT/8OD1pxvAoV2jSfBnXVuuRwxjiKeDJOGzgod7ctC8=
    gemspec: souyuz.gemspec
    on:
      tags: true
      branch: master
      repo: voydz/souyuz
  - provider: rubygems
    api_key:
      secure: HiYnlWSfaQo9+jezq3PrxNykDSCIIFDP1oxLVz77vsXRh8pJRCdD6NL8SFlHTT6OX40pMWKjK05F+pTcGtsqqmoe7LS/s+lBYsVxEaHLkDz/JKaOLrhnm9P0V3hYxj239o9St1Ro58wKbQYWjyLXdvKk5xVMrp9XbmKYEGpimNk4YUYmvYA9+pVVTSUdlt15L109wC/92tJigTaNNMn3T2KgetdgZQEUn+8mlv1hZvb6fcCdPn5PCP/5nZAGL9dRuL16ztMQhlGQCvtutIU5dbsZsaNg/WF5JReCgUbF+mnUAImmRO9oKNQJAcp3PAhlJ73GeZyewQD7saWqQqYoZ4nkQQW6siqKRE9phdWoe2hU/AlAhpz3ZcJAgPI22MX2pHwwfEwTHfq9S4bsH6ZzVUbY8RMuEEDFwgly74AZzak2TP0bpGMziP1UzgmsPQYiNCT4EUvIQfh40oC0pi1/XOLT9vqFuCf2GcFKtnLQJGlBxuPEIvZfqNDWHts5NuMP8JKAbMB5lUFjHEGDkEmjpT8ebkHxLEivsXhWSHG9i0mO8obbNJCKJQ6n32dtyPY0twP/PjEBYmBamcLIiLACuens578GoF6Bhs6DSGF9zd6uHKQqORDpi4pp6QcUFgqUkT/8OD1pxvAoV2jSfBnXVuuRwxjiKeDJOGzgod7ctC8=
    gemspec: fastlane-plugin-souyuz/fastlane-plugin-souyuz.gemspec
    on:
      tags: true
      branch: master
      repo: voydz/souyuz
